ig_username = ""
ig_password = ""
""" host of database (maybe localhost) """
db_host = ""
""" username of database """
db_username = ""
""" password of database """
db_password = ""
""" name of database """
db_name = ""
